version: '3.8'

services:
  russiankisa:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: russiankisa-portfolio
    
    # Здоровье контейнера
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3 